//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace RestAPI
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SedogoDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SedogoDBEntities object using the connection string found in the 'SedogoDBEntities' section of the application configuration file.
        /// </summary>
        public SedogoDBEntities() : base("name=SedogoDBEntities", "SedogoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SedogoDBEntities object.
        /// </summary>
        public SedogoDBEntities(string connectionString) : base(connectionString, "SedogoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SedogoDBEntities object.
        /// </summary>
        public SedogoDBEntities(EntityConnection connection) : base(connection, "SedogoDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Function Imports
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        public ObjectResult<spSelectUserDetails_Result> spSelectUserDetails(Nullable<global::System.Int32> userID)
        {
            ObjectParameter userIDParameter;
            if (userID.HasValue)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spSelectUserDetails_Result>("spSelectUserDetails", userIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="emailAddress">No Metadata Documentation available.</param>
        public ObjectResult<spVerifyUserLogin_Result> spVerifyUserLogin(global::System.String emailAddress)
        {
            ObjectParameter emailAddressParameter;
            if (emailAddress != null)
            {
                emailAddressParameter = new ObjectParameter("EmailAddress", emailAddress);
            }
            else
            {
                emailAddressParameter = new ObjectParameter("EmailAddress", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spVerifyUserLogin_Result>("spVerifyUserLogin", emailAddressParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="emailAddress">No Metadata Documentation available.</param>
        /// <param name="gUID">No Metadata Documentation available.</param>
        /// <param name="firstName">No Metadata Documentation available.</param>
        /// <param name="lastName">No Metadata Documentation available.</param>
        /// <param name="gender">No Metadata Documentation available.</param>
        /// <param name="homeTown">No Metadata Documentation available.</param>
        /// <param name="birthday">No Metadata Documentation available.</param>
        /// <param name="countryID">No Metadata Documentation available.</param>
        /// <param name="languageID">No Metadata Documentation available.</param>
        /// <param name="timezoneID">No Metadata Documentation available.</param>
        /// <param name="profileText">No Metadata Documentation available.</param>
        /// <param name="createdDate">No Metadata Documentation available.</param>
        /// <param name="createdByFullName">No Metadata Documentation available.</param>
        /// <param name="lastUpdatedDate">No Metadata Documentation available.</param>
        /// <param name="lastUpdatedByFullName">No Metadata Documentation available.</param>
        /// <param name="userID">No Metadata Documentation available.</param>
        public int spAddUser(global::System.String emailAddress, global::System.String gUID, global::System.String firstName, global::System.String lastName, global::System.String gender, global::System.String homeTown, Nullable<global::System.DateTime> birthday, Nullable<global::System.Int32> countryID, Nullable<global::System.Int32> languageID, Nullable<global::System.Int32> timezoneID, global::System.String profileText, Nullable<global::System.DateTime> createdDate, global::System.String createdByFullName, Nullable<global::System.DateTime> lastUpdatedDate, global::System.String lastUpdatedByFullName, ObjectParameter userID)
        {
            ObjectParameter emailAddressParameter;
            if (emailAddress != null)
            {
                emailAddressParameter = new ObjectParameter("EmailAddress", emailAddress);
            }
            else
            {
                emailAddressParameter = new ObjectParameter("EmailAddress", typeof(global::System.String));
            }
    
            ObjectParameter gUIDParameter;
            if (gUID != null)
            {
                gUIDParameter = new ObjectParameter("GUID", gUID);
            }
            else
            {
                gUIDParameter = new ObjectParameter("GUID", typeof(global::System.String));
            }
    
            ObjectParameter firstNameParameter;
            if (firstName != null)
            {
                firstNameParameter = new ObjectParameter("FirstName", firstName);
            }
            else
            {
                firstNameParameter = new ObjectParameter("FirstName", typeof(global::System.String));
            }
    
            ObjectParameter lastNameParameter;
            if (lastName != null)
            {
                lastNameParameter = new ObjectParameter("LastName", lastName);
            }
            else
            {
                lastNameParameter = new ObjectParameter("LastName", typeof(global::System.String));
            }
    
            ObjectParameter genderParameter;
            if (gender != null)
            {
                genderParameter = new ObjectParameter("Gender", gender);
            }
            else
            {
                genderParameter = new ObjectParameter("Gender", typeof(global::System.String));
            }
    
            ObjectParameter homeTownParameter;
            if (homeTown != null)
            {
                homeTownParameter = new ObjectParameter("HomeTown", homeTown);
            }
            else
            {
                homeTownParameter = new ObjectParameter("HomeTown", typeof(global::System.String));
            }
    
            ObjectParameter birthdayParameter;
            if (birthday.HasValue)
            {
                birthdayParameter = new ObjectParameter("Birthday", birthday);
            }
            else
            {
                birthdayParameter = new ObjectParameter("Birthday", typeof(global::System.DateTime));
            }
    
            ObjectParameter countryIDParameter;
            if (countryID.HasValue)
            {
                countryIDParameter = new ObjectParameter("CountryID", countryID);
            }
            else
            {
                countryIDParameter = new ObjectParameter("CountryID", typeof(global::System.Int32));
            }
    
            ObjectParameter languageIDParameter;
            if (languageID.HasValue)
            {
                languageIDParameter = new ObjectParameter("LanguageID", languageID);
            }
            else
            {
                languageIDParameter = new ObjectParameter("LanguageID", typeof(global::System.Int32));
            }
    
            ObjectParameter timezoneIDParameter;
            if (timezoneID.HasValue)
            {
                timezoneIDParameter = new ObjectParameter("TimezoneID", timezoneID);
            }
            else
            {
                timezoneIDParameter = new ObjectParameter("TimezoneID", typeof(global::System.Int32));
            }
    
            ObjectParameter profileTextParameter;
            if (profileText != null)
            {
                profileTextParameter = new ObjectParameter("ProfileText", profileText);
            }
            else
            {
                profileTextParameter = new ObjectParameter("ProfileText", typeof(global::System.String));
            }
    
            ObjectParameter createdDateParameter;
            if (createdDate.HasValue)
            {
                createdDateParameter = new ObjectParameter("CreatedDate", createdDate);
            }
            else
            {
                createdDateParameter = new ObjectParameter("CreatedDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter createdByFullNameParameter;
            if (createdByFullName != null)
            {
                createdByFullNameParameter = new ObjectParameter("CreatedByFullName", createdByFullName);
            }
            else
            {
                createdByFullNameParameter = new ObjectParameter("CreatedByFullName", typeof(global::System.String));
            }
    
            ObjectParameter lastUpdatedDateParameter;
            if (lastUpdatedDate.HasValue)
            {
                lastUpdatedDateParameter = new ObjectParameter("LastUpdatedDate", lastUpdatedDate);
            }
            else
            {
                lastUpdatedDateParameter = new ObjectParameter("LastUpdatedDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter lastUpdatedByFullNameParameter;
            if (lastUpdatedByFullName != null)
            {
                lastUpdatedByFullNameParameter = new ObjectParameter("LastUpdatedByFullName", lastUpdatedByFullName);
            }
            else
            {
                lastUpdatedByFullNameParameter = new ObjectParameter("LastUpdatedByFullName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spAddUser", emailAddressParameter, gUIDParameter, firstNameParameter, lastNameParameter, genderParameter, homeTownParameter, birthdayParameter, countryIDParameter, languageIDParameter, timezoneIDParameter, profileTextParameter, createdDateParameter, createdByFullNameParameter, lastUpdatedDateParameter, lastUpdatedByFullNameParameter, userID);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="emailAddress">No Metadata Documentation available.</param>
        public ObjectResult<spVerifyAdministratorLogin_Result> spVerifyAdministratorLogin(global::System.String emailAddress)
        {
            ObjectParameter emailAddressParameter;
            if (emailAddress != null)
            {
                emailAddressParameter = new ObjectParameter("EmailAddress", emailAddress);
            }
            else
            {
                emailAddressParameter = new ObjectParameter("EmailAddress", typeof(global::System.String));
            }
    
            return base.ExecuteFunction<spVerifyAdministratorLogin_Result>("spVerifyAdministratorLogin", emailAddressParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="administratorID">No Metadata Documentation available.</param>
        public ObjectResult<spSelectAdministratorDetails_Result> spSelectAdministratorDetails(Nullable<global::System.Int32> administratorID)
        {
            ObjectParameter administratorIDParameter;
            if (administratorID.HasValue)
            {
                administratorIDParameter = new ObjectParameter("AdministratorID", administratorID);
            }
            else
            {
                administratorIDParameter = new ObjectParameter("AdministratorID", typeof(global::System.Int32));
            }
    
            return base.ExecuteFunction<spSelectAdministratorDetails_Result>("spSelectAdministratorDetails", administratorIDParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="profilePicFilename">No Metadata Documentation available.</param>
        /// <param name="profilePicThumbnail">No Metadata Documentation available.</param>
        /// <param name="profilePicPreview">No Metadata Documentation available.</param>
        /// <param name="lastUpdatedDate">No Metadata Documentation available.</param>
        /// <param name="lastUpdatedByFullName">No Metadata Documentation available.</param>
        public int spUpdateUserProfilePic(Nullable<global::System.Int32> userID, global::System.String profilePicFilename, global::System.String profilePicThumbnail, global::System.String profilePicPreview, Nullable<global::System.DateTime> lastUpdatedDate, global::System.String lastUpdatedByFullName)
        {
            ObjectParameter userIDParameter;
            if (userID.HasValue)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.Int32));
            }
    
            ObjectParameter profilePicFilenameParameter;
            if (profilePicFilename != null)
            {
                profilePicFilenameParameter = new ObjectParameter("ProfilePicFilename", profilePicFilename);
            }
            else
            {
                profilePicFilenameParameter = new ObjectParameter("ProfilePicFilename", typeof(global::System.String));
            }
    
            ObjectParameter profilePicThumbnailParameter;
            if (profilePicThumbnail != null)
            {
                profilePicThumbnailParameter = new ObjectParameter("ProfilePicThumbnail", profilePicThumbnail);
            }
            else
            {
                profilePicThumbnailParameter = new ObjectParameter("ProfilePicThumbnail", typeof(global::System.String));
            }
    
            ObjectParameter profilePicPreviewParameter;
            if (profilePicPreview != null)
            {
                profilePicPreviewParameter = new ObjectParameter("ProfilePicPreview", profilePicPreview);
            }
            else
            {
                profilePicPreviewParameter = new ObjectParameter("ProfilePicPreview", typeof(global::System.String));
            }
    
            ObjectParameter lastUpdatedDateParameter;
            if (lastUpdatedDate.HasValue)
            {
                lastUpdatedDateParameter = new ObjectParameter("LastUpdatedDate", lastUpdatedDate);
            }
            else
            {
                lastUpdatedDateParameter = new ObjectParameter("LastUpdatedDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter lastUpdatedByFullNameParameter;
            if (lastUpdatedByFullName != null)
            {
                lastUpdatedByFullNameParameter = new ObjectParameter("LastUpdatedByFullName", lastUpdatedByFullName);
            }
            else
            {
                lastUpdatedByFullNameParameter = new ObjectParameter("LastUpdatedByFullName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spUpdateUserProfilePic", userIDParameter, profilePicFilenameParameter, profilePicThumbnailParameter, profilePicPreviewParameter, lastUpdatedDateParameter, lastUpdatedByFullNameParameter);
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        /// <param name="userID">No Metadata Documentation available.</param>
        /// <param name="userPassword">No Metadata Documentation available.</param>
        /// <param name="lastUpdatedDate">No Metadata Documentation available.</param>
        /// <param name="lastUpdatedByFullName">No Metadata Documentation available.</param>
        public int spUpdateUserPassword(Nullable<global::System.Int32> userID, global::System.String userPassword, Nullable<global::System.DateTime> lastUpdatedDate, global::System.String lastUpdatedByFullName)
        {
            ObjectParameter userIDParameter;
            if (userID.HasValue)
            {
                userIDParameter = new ObjectParameter("UserID", userID);
            }
            else
            {
                userIDParameter = new ObjectParameter("UserID", typeof(global::System.Int32));
            }
    
            ObjectParameter userPasswordParameter;
            if (userPassword != null)
            {
                userPasswordParameter = new ObjectParameter("UserPassword", userPassword);
            }
            else
            {
                userPasswordParameter = new ObjectParameter("UserPassword", typeof(global::System.String));
            }
    
            ObjectParameter lastUpdatedDateParameter;
            if (lastUpdatedDate.HasValue)
            {
                lastUpdatedDateParameter = new ObjectParameter("LastUpdatedDate", lastUpdatedDate);
            }
            else
            {
                lastUpdatedDateParameter = new ObjectParameter("LastUpdatedDate", typeof(global::System.DateTime));
            }
    
            ObjectParameter lastUpdatedByFullNameParameter;
            if (lastUpdatedByFullName != null)
            {
                lastUpdatedByFullNameParameter = new ObjectParameter("LastUpdatedByFullName", lastUpdatedByFullName);
            }
            else
            {
                lastUpdatedByFullNameParameter = new ObjectParameter("LastUpdatedByFullName", typeof(global::System.String));
            }
    
            return base.ExecuteFunction("spUpdateUserPassword", userIDParameter, userPasswordParameter, lastUpdatedDateParameter, lastUpdatedByFullNameParameter);
        }

        #endregion
    }
    

    #endregion
    
    #region ComplexTypes
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="sedogoDBModel", Name="spSelectAdministratorDetails_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spSelectAdministratorDetails_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spSelectAdministratorDetails_Result object.
        /// </summary>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        /// <param name="loginEnabled">Initial value of the LoginEnabled property.</param>
        /// <param name="failedLoginCount">Initial value of the FailedLoginCount property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="createdByFullName">Initial value of the CreatedByFullName property.</param>
        /// <param name="lastUpdatedDate">Initial value of the LastUpdatedDate property.</param>
        /// <param name="lastUpdatedByFullName">Initial value of the LastUpdatedByFullName property.</param>
        public static spSelectAdministratorDetails_Result CreatespSelectAdministratorDetails_Result(global::System.String emailAddress, global::System.Boolean deleted, global::System.Boolean loginEnabled, global::System.Int32 failedLoginCount, global::System.DateTime createdDate, global::System.String createdByFullName, global::System.DateTime lastUpdatedDate, global::System.String lastUpdatedByFullName)
        {
            spSelectAdministratorDetails_Result spSelectAdministratorDetails_Result = new spSelectAdministratorDetails_Result();
            spSelectAdministratorDetails_Result.EmailAddress = emailAddress;
            spSelectAdministratorDetails_Result.Deleted = deleted;
            spSelectAdministratorDetails_Result.LoginEnabled = loginEnabled;
            spSelectAdministratorDetails_Result.FailedLoginCount = failedLoginCount;
            spSelectAdministratorDetails_Result.CreatedDate = createdDate;
            spSelectAdministratorDetails_Result.CreatedByFullName = createdByFullName;
            spSelectAdministratorDetails_Result.LastUpdatedDate = lastUpdatedDate;
            spSelectAdministratorDetails_Result.LastUpdatedByFullName = lastUpdatedByFullName;
            return spSelectAdministratorDetails_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdministratorName
        {
            get
            {
                return _AdministratorName;
            }
            set
            {
                OnAdministratorNameChanging(value);
                ReportPropertyChanging("AdministratorName");
                _AdministratorName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdministratorName");
                OnAdministratorNameChanged();
            }
        }
        private global::System.String _AdministratorName;
        partial void OnAdministratorNameChanging(global::System.String value);
        partial void OnAdministratorNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedDate
        {
            get
            {
                return _DeletedDate;
            }
            set
            {
                OnDeletedDateChanging(value);
                ReportPropertyChanging("DeletedDate");
                _DeletedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedDate");
                OnDeletedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedDate;
        partial void OnDeletedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoginEnabled
        {
            get
            {
                return _LoginEnabled;
            }
            set
            {
                OnLoginEnabledChanging(value);
                ReportPropertyChanging("LoginEnabled");
                _LoginEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginEnabled");
                OnLoginEnabledChanged();
            }
        }
        private global::System.Boolean _LoginEnabled;
        partial void OnLoginEnabledChanging(global::System.Boolean value);
        partial void OnLoginEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdministratorPassword
        {
            get
            {
                return _AdministratorPassword;
            }
            set
            {
                OnAdministratorPasswordChanging(value);
                ReportPropertyChanging("AdministratorPassword");
                _AdministratorPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdministratorPassword");
                OnAdministratorPasswordChanged();
            }
        }
        private global::System.String _AdministratorPassword;
        partial void OnAdministratorPasswordChanging(global::System.String value);
        partial void OnAdministratorPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FailedLoginCount
        {
            get
            {
                return _FailedLoginCount;
            }
            set
            {
                OnFailedLoginCountChanging(value);
                ReportPropertyChanging("FailedLoginCount");
                _FailedLoginCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedLoginCount");
                OnFailedLoginCountChanged();
            }
        }
        private global::System.Int32 _FailedLoginCount;
        partial void OnFailedLoginCountChanging(global::System.Int32 value);
        partial void OnFailedLoginCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PasswordExpiryDate
        {
            get
            {
                return _PasswordExpiryDate;
            }
            set
            {
                OnPasswordExpiryDateChanging(value);
                ReportPropertyChanging("PasswordExpiryDate");
                _PasswordExpiryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpiryDate");
                OnPasswordExpiryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PasswordExpiryDate;
        partial void OnPasswordExpiryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPasswordExpiryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedByFullName
        {
            get
            {
                return _CreatedByFullName;
            }
            set
            {
                OnCreatedByFullNameChanging(value);
                ReportPropertyChanging("CreatedByFullName");
                _CreatedByFullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedByFullName");
                OnCreatedByFullNameChanged();
            }
        }
        private global::System.String _CreatedByFullName;
        partial void OnCreatedByFullNameChanging(global::System.String value);
        partial void OnCreatedByFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                OnLastUpdatedDateChanging(value);
                ReportPropertyChanging("LastUpdatedDate");
                _LastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdatedDate");
                OnLastUpdatedDateChanged();
            }
        }
        private global::System.DateTime _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(global::System.DateTime value);
        partial void OnLastUpdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedByFullName
        {
            get
            {
                return _LastUpdatedByFullName;
            }
            set
            {
                OnLastUpdatedByFullNameChanging(value);
                ReportPropertyChanging("LastUpdatedByFullName");
                _LastUpdatedByFullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastUpdatedByFullName");
                OnLastUpdatedByFullNameChanged();
            }
        }
        private global::System.String _LastUpdatedByFullName;
        partial void OnLastUpdatedByFullNameChanging(global::System.String value);
        partial void OnLastUpdatedByFullNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="sedogoDBModel", Name="spSelectUserDetails_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spSelectUserDetails_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spSelectUserDetails_Result object.
        /// </summary>
        /// <param name="gUID">Initial value of the GUID property.</param>
        /// <param name="emailAddress">Initial value of the EmailAddress property.</param>
        /// <param name="gender">Initial value of the Gender property.</param>
        /// <param name="deleted">Initial value of the Deleted property.</param>
        /// <param name="countryID">Initial value of the CountryID property.</param>
        /// <param name="languageID">Initial value of the LanguageID property.</param>
        /// <param name="timezoneID">Initial value of the TimezoneID property.</param>
        /// <param name="enableSendEmails">Initial value of the EnableSendEmails property.</param>
        /// <param name="loginEnabled">Initial value of the LoginEnabled property.</param>
        /// <param name="failedLoginCount">Initial value of the FailedLoginCount property.</param>
        /// <param name="createdDate">Initial value of the CreatedDate property.</param>
        /// <param name="createdByFullName">Initial value of the CreatedByFullName property.</param>
        /// <param name="lastUpdatedDate">Initial value of the LastUpdatedDate property.</param>
        /// <param name="lastUpdatedByFullName">Initial value of the LastUpdatedByFullName property.</param>
        public static spSelectUserDetails_Result CreatespSelectUserDetails_Result(global::System.String gUID, global::System.String emailAddress, global::System.String gender, global::System.Boolean deleted, global::System.Int32 countryID, global::System.Int32 languageID, global::System.Int32 timezoneID, global::System.Boolean enableSendEmails, global::System.Boolean loginEnabled, global::System.Int32 failedLoginCount, global::System.DateTime createdDate, global::System.String createdByFullName, global::System.DateTime lastUpdatedDate, global::System.String lastUpdatedByFullName)
        {
            spSelectUserDetails_Result spSelectUserDetails_Result = new spSelectUserDetails_Result();
            spSelectUserDetails_Result.GUID = gUID;
            spSelectUserDetails_Result.EmailAddress = emailAddress;
            spSelectUserDetails_Result.Gender = gender;
            spSelectUserDetails_Result.Deleted = deleted;
            spSelectUserDetails_Result.CountryID = countryID;
            spSelectUserDetails_Result.LanguageID = languageID;
            spSelectUserDetails_Result.TimezoneID = timezoneID;
            spSelectUserDetails_Result.EnableSendEmails = enableSendEmails;
            spSelectUserDetails_Result.LoginEnabled = loginEnabled;
            spSelectUserDetails_Result.FailedLoginCount = failedLoginCount;
            spSelectUserDetails_Result.CreatedDate = createdDate;
            spSelectUserDetails_Result.CreatedByFullName = createdByFullName;
            spSelectUserDetails_Result.LastUpdatedDate = lastUpdatedDate;
            spSelectUserDetails_Result.LastUpdatedByFullName = lastUpdatedByFullName;
            return spSelectUserDetails_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String GUID
        {
            get
            {
                return _GUID;
            }
            set
            {
                OnGUIDChanging(value);
                ReportPropertyChanging("GUID");
                _GUID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("GUID");
                OnGUIDChanged();
            }
        }
        private global::System.String _GUID;
        partial void OnGUIDChanging(global::System.String value);
        partial void OnGUIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String EmailAddress
        {
            get
            {
                return _EmailAddress;
            }
            set
            {
                OnEmailAddressChanging(value);
                ReportPropertyChanging("EmailAddress");
                _EmailAddress = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("EmailAddress");
                OnEmailAddressChanged();
            }
        }
        private global::System.String _EmailAddress;
        partial void OnEmailAddressChanging(global::System.String value);
        partial void OnEmailAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gender
        {
            get
            {
                return _Gender;
            }
            set
            {
                OnGenderChanging(value);
                ReportPropertyChanging("Gender");
                _Gender = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gender");
                OnGenderChanged();
            }
        }
        private global::System.String _Gender;
        partial void OnGenderChanging(global::System.String value);
        partial void OnGenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Deleted
        {
            get
            {
                return _Deleted;
            }
            set
            {
                OnDeletedChanging(value);
                ReportPropertyChanging("Deleted");
                _Deleted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Deleted");
                OnDeletedChanged();
            }
        }
        private global::System.Boolean _Deleted;
        partial void OnDeletedChanging(global::System.Boolean value);
        partial void OnDeletedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DeletedDate
        {
            get
            {
                return _DeletedDate;
            }
            set
            {
                OnDeletedDateChanging(value);
                ReportPropertyChanging("DeletedDate");
                _DeletedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DeletedDate");
                OnDeletedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DeletedDate;
        partial void OnDeletedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDeletedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HomeTown
        {
            get
            {
                return _HomeTown;
            }
            set
            {
                OnHomeTownChanging(value);
                ReportPropertyChanging("HomeTown");
                _HomeTown = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HomeTown");
                OnHomeTownChanged();
            }
        }
        private global::System.String _HomeTown;
        partial void OnHomeTownChanging(global::System.String value);
        partial void OnHomeTownChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfilePicFilename
        {
            get
            {
                return _ProfilePicFilename;
            }
            set
            {
                OnProfilePicFilenameChanging(value);
                ReportPropertyChanging("ProfilePicFilename");
                _ProfilePicFilename = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProfilePicFilename");
                OnProfilePicFilenameChanged();
            }
        }
        private global::System.String _ProfilePicFilename;
        partial void OnProfilePicFilenameChanging(global::System.String value);
        partial void OnProfilePicFilenameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfilePicThumbnail
        {
            get
            {
                return _ProfilePicThumbnail;
            }
            set
            {
                OnProfilePicThumbnailChanging(value);
                ReportPropertyChanging("ProfilePicThumbnail");
                _ProfilePicThumbnail = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProfilePicThumbnail");
                OnProfilePicThumbnailChanged();
            }
        }
        private global::System.String _ProfilePicThumbnail;
        partial void OnProfilePicThumbnailChanging(global::System.String value);
        partial void OnProfilePicThumbnailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfilePicPreview
        {
            get
            {
                return _ProfilePicPreview;
            }
            set
            {
                OnProfilePicPreviewChanging(value);
                ReportPropertyChanging("ProfilePicPreview");
                _ProfilePicPreview = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProfilePicPreview");
                OnProfilePicPreviewChanged();
            }
        }
        private global::System.String _ProfilePicPreview;
        partial void OnProfilePicPreviewChanging(global::System.String value);
        partial void OnProfilePicPreviewChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ProfileText
        {
            get
            {
                return _ProfileText;
            }
            set
            {
                OnProfileTextChanging(value);
                ReportPropertyChanging("ProfileText");
                _ProfileText = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ProfileText");
                OnProfileTextChanged();
            }
        }
        private global::System.String _ProfileText;
        partial void OnProfileTextChanging(global::System.String value);
        partial void OnProfileTextChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CountryID
        {
            get
            {
                return _CountryID;
            }
            set
            {
                OnCountryIDChanging(value);
                ReportPropertyChanging("CountryID");
                _CountryID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CountryID");
                OnCountryIDChanged();
            }
        }
        private global::System.Int32 _CountryID;
        partial void OnCountryIDChanging(global::System.Int32 value);
        partial void OnCountryIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LanguageID
        {
            get
            {
                return _LanguageID;
            }
            set
            {
                OnLanguageIDChanging(value);
                ReportPropertyChanging("LanguageID");
                _LanguageID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LanguageID");
                OnLanguageIDChanged();
            }
        }
        private global::System.Int32 _LanguageID;
        partial void OnLanguageIDChanging(global::System.Int32 value);
        partial void OnLanguageIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TimezoneID
        {
            get
            {
                return _TimezoneID;
            }
            set
            {
                OnTimezoneIDChanging(value);
                ReportPropertyChanging("TimezoneID");
                _TimezoneID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TimezoneID");
                OnTimezoneIDChanged();
            }
        }
        private global::System.Int32 _TimezoneID;
        partial void OnTimezoneIDChanging(global::System.Int32 value);
        partial void OnTimezoneIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean EnableSendEmails
        {
            get
            {
                return _EnableSendEmails;
            }
            set
            {
                OnEnableSendEmailsChanging(value);
                ReportPropertyChanging("EnableSendEmails");
                _EnableSendEmails = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("EnableSendEmails");
                OnEnableSendEmailsChanged();
            }
        }
        private global::System.Boolean _EnableSendEmails;
        partial void OnEnableSendEmailsChanging(global::System.Boolean value);
        partial void OnEnableSendEmailsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoginEnabled
        {
            get
            {
                return _LoginEnabled;
            }
            set
            {
                OnLoginEnabledChanging(value);
                ReportPropertyChanging("LoginEnabled");
                _LoginEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginEnabled");
                OnLoginEnabledChanged();
            }
        }
        private global::System.Boolean _LoginEnabled;
        partial void OnLoginEnabledChanging(global::System.Boolean value);
        partial void OnLoginEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FailedLoginCount
        {
            get
            {
                return _FailedLoginCount;
            }
            set
            {
                OnFailedLoginCountChanging(value);
                ReportPropertyChanging("FailedLoginCount");
                _FailedLoginCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedLoginCount");
                OnFailedLoginCountChanged();
            }
        }
        private global::System.Int32 _FailedLoginCount;
        partial void OnFailedLoginCountChanging(global::System.Int32 value);
        partial void OnFailedLoginCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PasswordExpiryDate
        {
            get
            {
                return _PasswordExpiryDate;
            }
            set
            {
                OnPasswordExpiryDateChanging(value);
                ReportPropertyChanging("PasswordExpiryDate");
                _PasswordExpiryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpiryDate");
                OnPasswordExpiryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PasswordExpiryDate;
        partial void OnPasswordExpiryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPasswordExpiryDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> LastLoginDate
        {
            get
            {
                return _LastLoginDate;
            }
            set
            {
                OnLastLoginDateChanging(value);
                ReportPropertyChanging("LastLoginDate");
                _LastLoginDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastLoginDate");
                OnLastLoginDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _LastLoginDate;
        partial void OnLastLoginDateChanging(Nullable<global::System.DateTime> value);
        partial void OnLastLoginDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreatedDate
        {
            get
            {
                return _CreatedDate;
            }
            set
            {
                OnCreatedDateChanging(value);
                ReportPropertyChanging("CreatedDate");
                _CreatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatedDate");
                OnCreatedDateChanged();
            }
        }
        private global::System.DateTime _CreatedDate;
        partial void OnCreatedDateChanging(global::System.DateTime value);
        partial void OnCreatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String CreatedByFullName
        {
            get
            {
                return _CreatedByFullName;
            }
            set
            {
                OnCreatedByFullNameChanging(value);
                ReportPropertyChanging("CreatedByFullName");
                _CreatedByFullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("CreatedByFullName");
                OnCreatedByFullNameChanged();
            }
        }
        private global::System.String _CreatedByFullName;
        partial void OnCreatedByFullNameChanging(global::System.String value);
        partial void OnCreatedByFullNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime LastUpdatedDate
        {
            get
            {
                return _LastUpdatedDate;
            }
            set
            {
                OnLastUpdatedDateChanging(value);
                ReportPropertyChanging("LastUpdatedDate");
                _LastUpdatedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LastUpdatedDate");
                OnLastUpdatedDateChanged();
            }
        }
        private global::System.DateTime _LastUpdatedDate;
        partial void OnLastUpdatedDateChanging(global::System.DateTime value);
        partial void OnLastUpdatedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastUpdatedByFullName
        {
            get
            {
                return _LastUpdatedByFullName;
            }
            set
            {
                OnLastUpdatedByFullNameChanging(value);
                ReportPropertyChanging("LastUpdatedByFullName");
                _LastUpdatedByFullName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastUpdatedByFullName");
                OnLastUpdatedByFullNameChanged();
            }
        }
        private global::System.String _LastUpdatedByFullName;
        partial void OnLastUpdatedByFullNameChanging(global::System.String value);
        partial void OnLastUpdatedByFullNameChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="sedogoDBModel", Name="spVerifyAdministratorLogin_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spVerifyAdministratorLogin_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spVerifyAdministratorLogin_Result object.
        /// </summary>
        /// <param name="administratorID">Initial value of the AdministratorID property.</param>
        /// <param name="loginEnabled">Initial value of the LoginEnabled property.</param>
        /// <param name="failedLoginCount">Initial value of the FailedLoginCount property.</param>
        public static spVerifyAdministratorLogin_Result CreatespVerifyAdministratorLogin_Result(global::System.Int32 administratorID, global::System.Boolean loginEnabled, global::System.Int32 failedLoginCount)
        {
            spVerifyAdministratorLogin_Result spVerifyAdministratorLogin_Result = new spVerifyAdministratorLogin_Result();
            spVerifyAdministratorLogin_Result.AdministratorID = administratorID;
            spVerifyAdministratorLogin_Result.LoginEnabled = loginEnabled;
            spVerifyAdministratorLogin_Result.FailedLoginCount = failedLoginCount;
            return spVerifyAdministratorLogin_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 AdministratorID
        {
            get
            {
                return _AdministratorID;
            }
            set
            {
                OnAdministratorIDChanging(value);
                ReportPropertyChanging("AdministratorID");
                _AdministratorID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AdministratorID");
                OnAdministratorIDChanged();
            }
        }
        private global::System.Int32 _AdministratorID;
        partial void OnAdministratorIDChanging(global::System.Int32 value);
        partial void OnAdministratorIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoginEnabled
        {
            get
            {
                return _LoginEnabled;
            }
            set
            {
                OnLoginEnabledChanging(value);
                ReportPropertyChanging("LoginEnabled");
                _LoginEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginEnabled");
                OnLoginEnabledChanged();
            }
        }
        private global::System.Boolean _LoginEnabled;
        partial void OnLoginEnabledChanging(global::System.Boolean value);
        partial void OnLoginEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AdministratorPassword
        {
            get
            {
                return _AdministratorPassword;
            }
            set
            {
                OnAdministratorPasswordChanging(value);
                ReportPropertyChanging("AdministratorPassword");
                _AdministratorPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AdministratorPassword");
                OnAdministratorPasswordChanged();
            }
        }
        private global::System.String _AdministratorPassword;
        partial void OnAdministratorPasswordChanging(global::System.String value);
        partial void OnAdministratorPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FailedLoginCount
        {
            get
            {
                return _FailedLoginCount;
            }
            set
            {
                OnFailedLoginCountChanging(value);
                ReportPropertyChanging("FailedLoginCount");
                _FailedLoginCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedLoginCount");
                OnFailedLoginCountChanged();
            }
        }
        private global::System.Int32 _FailedLoginCount;
        partial void OnFailedLoginCountChanging(global::System.Int32 value);
        partial void OnFailedLoginCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PasswordExpiryDate
        {
            get
            {
                return _PasswordExpiryDate;
            }
            set
            {
                OnPasswordExpiryDateChanging(value);
                ReportPropertyChanging("PasswordExpiryDate");
                _PasswordExpiryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpiryDate");
                OnPasswordExpiryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PasswordExpiryDate;
        partial void OnPasswordExpiryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPasswordExpiryDateChanged();

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmComplexTypeAttribute(NamespaceName="sedogoDBModel", Name="spVerifyUserLogin_Result")]
    [DataContractAttribute(IsReference=true)]
    [Serializable()]
    public partial class spVerifyUserLogin_Result : ComplexObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new spVerifyUserLogin_Result object.
        /// </summary>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="loginEnabled">Initial value of the LoginEnabled property.</param>
        /// <param name="failedLoginCount">Initial value of the FailedLoginCount property.</param>
        public static spVerifyUserLogin_Result CreatespVerifyUserLogin_Result(global::System.Int32 userID, global::System.Boolean loginEnabled, global::System.Int32 failedLoginCount)
        {
            spVerifyUserLogin_Result spVerifyUserLogin_Result = new spVerifyUserLogin_Result();
            spVerifyUserLogin_Result.UserID = userID;
            spVerifyUserLogin_Result.LoginEnabled = loginEnabled;
            spVerifyUserLogin_Result.FailedLoginCount = failedLoginCount;
            return spVerifyUserLogin_Result;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.Int32 _UserID;
        partial void OnUserIDChanging(global::System.Int32 value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean LoginEnabled
        {
            get
            {
                return _LoginEnabled;
            }
            set
            {
                OnLoginEnabledChanging(value);
                ReportPropertyChanging("LoginEnabled");
                _LoginEnabled = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LoginEnabled");
                OnLoginEnabledChanged();
            }
        }
        private global::System.Boolean _LoginEnabled;
        partial void OnLoginEnabledChanging(global::System.Boolean value);
        partial void OnLoginEnabledChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String UserPassword
        {
            get
            {
                return _UserPassword;
            }
            set
            {
                OnUserPasswordChanging(value);
                ReportPropertyChanging("UserPassword");
                _UserPassword = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("UserPassword");
                OnUserPasswordChanged();
            }
        }
        private global::System.String _UserPassword;
        partial void OnUserPasswordChanging(global::System.String value);
        partial void OnUserPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FailedLoginCount
        {
            get
            {
                return _FailedLoginCount;
            }
            set
            {
                OnFailedLoginCountChanging(value);
                ReportPropertyChanging("FailedLoginCount");
                _FailedLoginCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FailedLoginCount");
                OnFailedLoginCountChanged();
            }
        }
        private global::System.Int32 _FailedLoginCount;
        partial void OnFailedLoginCountChanging(global::System.Int32 value);
        partial void OnFailedLoginCountChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> PasswordExpiryDate
        {
            get
            {
                return _PasswordExpiryDate;
            }
            set
            {
                OnPasswordExpiryDateChanging(value);
                ReportPropertyChanging("PasswordExpiryDate");
                _PasswordExpiryDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PasswordExpiryDate");
                OnPasswordExpiryDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _PasswordExpiryDate;
        partial void OnPasswordExpiryDateChanging(Nullable<global::System.DateTime> value);
        partial void OnPasswordExpiryDateChanged();

        #endregion
    }

    #endregion
    
}
